
server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: "127.0.0.1"

combinationThreshold: 10000
minSlicingSize: 10000000
maxSlices: 10
interval: 50000 # in milliseconds
serviceName: cajrr
serviceHost: "127.0.0.1"
servicePort: 8080

consul: "127.0.0.1"

cluster: DevCluster
nodes:
  - host: 172.16.238.10
    port: 7199
  - host: 172.16.238.11
    port: 7199
  - host: 172.16.238.12
    port: 7199

keyspaces:
  - testspace

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
  appenders:
    - type: console
#    - type: file
#      currentLogFilename: /var/log/cajrr/cajrr.log
#      threshold: ALL
#      archive: true
#      archivedLogFilenamePattern: /var/log/cajrr/cajrr-%d.log
#      archivedFileCount: 5
#      timeZone: Asia/Yekaterinburg
      logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"

metrics:
  frequency: 1 minute
  reporters:
    - type: graphite
      host: 172.16.238.4
      port: 2003
      prefix: Cassandra.Repair.localhost