consulHost: localhost:8500
combinationThreshold: 10000
minSlicingSize: 10000000
maxSlices: 10
interval: 5000 # in milliseconds
cluster: DevCluster
nodes:
  - host: 172.16.238.10
    port: 7199
  - host: 172.16.238.11
    port: 7199
  - host: 172.16.238.12
    port: 7199

keyspaces:
  - testspace

logging:
  level: DEBUG
  loggers:
    io.dropwizard: DEBUG
    org.eclipse.jetty: DEBUG
  appenders:
    - type: console
#    - type: file
#      currentLogFilename: /var/log/cajrr/cajrr.log
#      threshold: ALL
#      archive: true
#      archivedLogFilenamePattern: /var/log/cajrr/cajrr-%d.log
#      archivedFileCount: 5
#      timeZone: Asia/Yekaterinburg
      logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"

#metrics:
#  frequency: 1 minute
#  reporters:
#    - type: graphite
#      host: graphite.example.com
#      port: 2003
#      prefix: DevOps.cajrr.localhost