clusters:
  - name: Test cluster
    ring:
      slices: 10
    nodes:
      - host: 172.16.238.10
        port: 7199
      - host: 172.16.238.11
      - host: 172.16.238.12


logging:
  level: DEBUG
  loggers:
    io.dropwizard: DEBUG
    org.eclipse.jetty: DEBUG
  appenders:
    - type: console
      logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"

#metrics:
#  frequency: 1 minute
#  reporters:
#    - type: graphite
#      host: graphite.example.com
#      port: 2003
#      prefix: DevOps.cajrr.localhost